import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import { ToastDestructive } from "@/components/toastError";
import Header from "@/components/header";
import NavigationBar from "@/components/navigationBar";

const geistSans = Poppins({
subsets: ["latin"],
weight: ["400"]
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
    <body>
        <div className={`${geistSans.className} antialiased`}>
          <Toaster />
          <ToastDestructive/>
          <Header />
          <NavigationBar />
          {children}
        </div>
    </body>
    </html>
  );
}
