import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast"
import ReactQueryProvider from "./providers/ReactQueryProvider";
 
const geistSans = Poppins({
subsets: ["latin"],
weight: ["400"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
    <body>
      <Toaster
          position="top-center"
          reverseOrder={false}
      />
        <div className={`${geistSans.className} antialiased`}>
        <ReactQueryProvider>
          {children}
        </ReactQueryProvider>
        </div>
    </body>
    </html>
  );
}