import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import Header from "@/components/header";
import NavigationBar from "@/components/navigationBar";
import { Toaster } from "@/components/ui/toaster";
import { ToastDestructive } from "@/components/toastError";

const geistSans = Poppins({
subsets: ["latin"],
weight: ["400"]
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
    <body>
        <Header />
        <NavigationBar />
        <div className={`${geistSans.className} antialiased`}>
          <Toaster />
          <ToastDestructive/>
          {children}
        </div>
        <Footer/>
    </body>
    </html>
  );
}
