import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
// import { ThemeProvider } from "@/components/themeProvider";
// import { ThemeProvider } from "@/components/themeProvider";

const geistSans = Poppins({
subsets: ["latin"],
weight: ["400"]
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
    <body>
      {/* <ThemeProvider
        attribute="class"
        defaultTheme="light"
        enableSystem
        disableTransitionOnChange
      >
      </ThemeProvider> */}
        <div className={`${geistSans.className} antialiased`}>
          {children}
        </div>
    </body>
    </html>
  );
}
